services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
      - "3001:3001"
    volumes:
      - ${FILES_PATH}:/app/files
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FILES_PATH=/app/files
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run server & npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge